name: Next.js Build and Deploy

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: 18.18.2

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout --orphan gh-pages
          git --work-tree=out --index-info -f
          mv out/* ./
          rmdir out
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages --force
        env:
          NODE_ENV: production

      - name: Cleanup
        run: |
          git checkout main
          git branch -D gh-pages
